### ISSUE TITLE
[Feature request] Example with 3DSecure 2 & Payment intent

### ISSUE THREAD

**Issue by M0dM** [stripe/stripe-billing-typographic#19]
Hi,

It would be very great if you could add and example with 3DSecure v2 support using payment intent API.
I am a little bit stuck with this workflow...

Regards,
M0dM

**Comment by ctrudeau-stripe** [comment]
Hey M0dm, adding support for 3DSecure and PaymentIntents [here](https://github.com/stripe/stripe-billing-typographic/pull/25). Let me know if there is anything I can help clarify for you if you're still stuck.
