### ISSUE TITLE
Subscription prices accumulate

### ISSUE THREAD

**Issue by samaddison** [stripe/stripe-billing-typographic#2]
If you subscribe to the starter plan, and then switch to the growth plan, you will be billed $30. I think it should only be $20? Aren't you effectively cancelling the starter plan and switching to the growth plan?

**Comment by mytototo** [comment]
Any news regarding this _potential_ issue?

**Comment by richjava** [comment]
This is a screenshot of what I get on the Stripe Subscriptions page when I start off on the starter plan and then immediately switch to the growth plan. Is it intended to be like this? Shouldn't the total bill for the month be $20?
![stripe-invoice](https://user-images.githubusercontent.com/489470/54859377-3bb6f500-4d71-11e9-8bfc-4e306fa169b5.PNG)

**Comment by ctrudeau-stripe** [comment]
When a customer moves from plan A to plan B in the middle of the billing cycle, we automatically calculate the proration to ensure that the customer pays what is expected. There are details for this in our subscriptions guide where we cover [upgrading and downgrading](https://stripe.com/docs/subscriptions/upgrading-downgrading).

Let's take an example where you have a customer subscribed to plan A for $50 monthly on the 1st of the month and then at the middle of the month you move him to plan B for $20/month we won't charge the customer immediately but we will calculate the proration for them and here's what would happen:
* The user paid $50 for the full month but he stops that plan mid month so so we create an invoice item indicating you owe him $25 (half a month).
* The user moved to plan B for half a month so he needs to pay for that time so we create an invoice item indicating he owes you $10 (half a month).

Those invoice items are then added to the upcoming invoice that would be created on the 1st of next month. Your customer would then owe you $20 + $10 and you owe him $25 so the invoice total would be $5.

**Comment by ctrudeau-stripe** [comment]
Closing this, happy to chat more about it if you have questions.
