### ISSUE TITLE
Signup / Login doesn't work with PostgreSQL

### ISSUE THREAD

**Issue by mytototo** [stripe/stripe-billing-typographic#6]
Hi there,

I tried the project in localhost both using `sqlite` and `pg`.

Using the `sqlite` adapter everything works fine.
However with the `pg` adapter the login and signup process is buggy on the server-side. It looks like the `id` of the user is not defined.

Any workaround regarding this issue ?
Thanks for your time.

**Comment by mg-stripe** [comment]
This should be fixed in #8. Let us know if you have any other issues!
